matrix:
  include:
    # linux focal build
    - name: "Linux - Clang - Ubuntu 20.04 LTS"
      language: cpp
      os: linux
      dist: focal
      env: CXX_EXE=/usr/bin/clang++-10 CC_EXE=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10
      cache:
        directories:
          - $HOME/.conan/data
      addons:
        apt:
          packages:
            - python3-pip
            - clang-10
            - libstdc++-10-dev
            - libc++abi-10-dev
            - ninja-build
            
      install:
        - pip install --user conan cmake
        
      script:
        - conan --version
        - cmake --version
        - mkdir build && cd build
        - conan install .. -s compiler=clang -s compiler.version=10 -s build_type=Debug --build missing
        - cmake .. -GNinja
        - cmake --build .
        - ctest